[versions]
agp = "8.3.1"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.12.0"
androidx-espresso-core = "3.5.1"
androidx-material = "1.11.0"
androidx-test-junit = "1.1.5"
compose = "1.6.3"
compose-plugin = "1.6.0"
firebaseBom = "32.7.4"
junit = "4.13.2"
kotlin = "1.9.22"
ktor = "2.3.8"
koin = "3.2.0"
cameraX = "1.3.2"
secrets-gradle-plugin = "2.0.1"
google-ai = "0.2.2"
gradle-buildconfig-plugin = "5.3.5"
lifecycleRuntimeCompose = "2.7.0"
kotlinx-serialization-plugin = "1.9.22"
kermit = "2.0.3"
kotlinx-datetime = "0.6.0-RC.2"
google-services = "4.4.1"
crashlytics = "2.9.9"
play-services-admob = "23.0.0"
material3 = "1.2.1"
material3Android = "1.2.1"
datastore = "1.0.0"

[libraries]
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
cameraX-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
cameraX-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
cameraX-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
cameraX-view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
cameraX-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraX" }
google-ai = { module ="com.google.ai.client.generativeai:generativeai", version.ref = "google-ai" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
play-services-admob = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-admob" }
material3 = { module = "com.google.android.material:material3", version.ref = "material3" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-cio", "ktor-client-serialization"]
koin = ["koin-core", "koin-test"]
cameraX = ["cameraX-core", "cameraX-camera2", "cameraX-lifecycle", "cameraX-view", "cameraX-extensions"]
androidx = ["androidx-core-ktx","androidx-appcompat", "androidx-material", "androidx-constraintlayout", "androidx-activity-compose"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig-plugin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization-plugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }


